# netlify.toml
# Этот файл сообщает Netlify, где найти наши бессерверные функции.

[build]
  # Директория, в которой находятся наши фронтенд-файлы (HTML, CSS, JS).
  # Оставляем корень, так как файлы лежат там.
  publish = "/"

[functions]
  # Директория, где лежат наши бессерверные функции-прокси.
  directory = "functions/" 

[dev]
  port = 8889 # Порт для самого Netlify Dev (основной)
  targetPort = 4001 # Порт для статического сервера (был занят 3999) 

# Правило для "красивых" URL на странице деталей аниме.
# Все запросы вида /anime/что-угодно будут обрабатываться файлом anime.html.
[[redirects]]
  from = "/anime/*"
  to = "/anime.html"
  status = 200 